apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: job-platform
resources:
  - rbac.yaml
  - pod-delete-experiment.yaml
  - pod-cpu-hog-experiment.yaml
  - pod-network-latency-experiment.yaml
