input {
  gelf {
    port => 12201
  }

  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [message] =~ "^{.*}$" {
    json {
      source => "message"
      target => "app"
      skip_on_invalid_json => true
    }
  }

  mutate {
    add_field => {
      "project" => "automated-chaos-testing-self-healing-microservices-platform"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "job-platform-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}

