apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: your-dockerhub-username/order-api
    newName: local/order-api
    newTag: jenkins-local
  - name: your-dockerhub-username/job-worker
    newName: local/job-worker
    newTag: jenkins-local
  - name: your-dockerhub-username/healing-controller
    newName: local/healing-controller
    newTag: jenkins-local
