apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - redpanda.yaml
  - redis.yaml
  - rbac.yaml
  - order-api.yaml
  - worker.yaml
  - healing-controller.yaml
  - hpa.yaml
  - pdb.yaml
