apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: job-platform
  labels:
    app: order-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: job-platform
        vault.hashicorp.com/agent-inject-secret-platform.env: secret/data/job-platform
        vault.hashicorp.com/agent-inject-template-platform.env: |
          {{- with secret "secret/data/job-platform" -}}
          API_TOKEN={{ .Data.data.api_token }}
          REDIS_PASSWORD={{ .Data.data.redis_password }}
          {{- end -}}
    spec:
      containers:
        - name: order-api
          image: your-dockerhub-username/order-api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: platform-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: job-platform
spec:
  selector:
    app: order-api
  ports:
    - name: http
      port: 8000
      targetPort: http
