apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: your-dockerhub-username/job-api
    newName: your-dockerhub-username/job-api
    newTag: dev
  - name: your-dockerhub-username/job-worker
    newName: your-dockerhub-username/job-worker
    newTag: dev
  - name: your-dockerhub-username/healing-controller
    newName: your-dockerhub-username/healing-controller
    newTag: dev

